In [1]:
# !pip install tensorflow

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
tf.__version__ #Version de tensorflow

'2.8.2'

Se crea una matriz de numpy de una sola dimensión de tamaño 25 sobre la que se aplicarán algunas operación.

In [4]:
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
# Convertir arreglo de numpy a Tensor usando `tf.Variable` (Mutable)
z = tf.Variable(x)
z

<tf.Variable 'Variable:0' shape=(25,) dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [6]:
# Convertir arreglo de numpy a Tensor usando `tf.constant` (Inmutable)
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [7]:
# Elevar al cuadrado el tensor de entrada x
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

Una característica de los tensores es que se pueden redimensionar.

Al redimensionar, asegúrese de considerar las dimensiones que incluirán todos los valores del tensor.

In [8]:
# Redimensionamiento del tensor x en una matriz de 5 x 5
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

Tenga en cuenta que recibirá un mensaje de error si elige una forma que
no se puede llenar exactamente con los valores del tensor dado.

In [11]:
# Intente cambiar los valores para el parámetro `shape`
tmp = tf.constant([1,2,3,4]) #Si el tamaño del vector va encontra de las dimensiones dara error
tf.reshape(tmp, shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

También es posible cambiar el tipo de dato de los valores dentro
el tensor. Ejecute la celda a continuación para cambiar el tipo de datos de `int` a `float`.

In [12]:
# Observe el cambio en el dtype tras modificar el tipo de dato
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [13]:
# Se define una constante para en la siguiente celda ver cómo funciona la vectorización y el broadcasting
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [14]:
# Multiplica el tensor 'x' con 'y'. Note como 'y' se multiplica por cada elemento de x
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [15]:
# Ahora se define una matriz que coincide con el número de elementos de fila en la matriz 'x'
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [16]:
# Resultado actualizado
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [17]:
# Ahora se suma 'y' como elemento a cada fila de 'x'
result = tf.add(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

In [18]:
# Otra forma de realizar la misma operación es sobrecargando el operador '+', de esta manera la operación resulta "más natural"
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

Al usar `tf.constant()`, se puede pasar una matriz 1D (un vector) y
establezcer el parámetro `shape` para convertir este vector en un arreglo multidimensional.

In [19]:
tf.constant([1,2,3,4], shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

Tenga en cuenta, sin embargo, que para `tf.Variable()`, la forma del tensor se
deriva de la forma dada por la matriz de entrada. Estableciendo `shape` igual a  `None` no redimensionará la matriz en 1D en una matriz multidimensional, y devolverá un `ValueError`.

In [20]:
try:
    # Esto producirá un `ValueError`
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # Ver lo que dice el `ValueError`
    print(v)

In this `tf.Variable` creation, the initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
