In [1]:
import numpy as np

## Broadcasting

Los arreglos de numpy se diferencian de las listas normales de Python debido a su capacidad para hacer broadcasting. Con las listas, solo puede operar con objetos del mismo tamaño y forma. Es decir, si se quisiera reemplazar los primeros 5 elementos de una lista con un nuevo valor, tendría que iterar sobre los 5 elementos de la lista. Con los arreglos de numpy, puede "transmitir" un solo valor a través de un conjunto más grande de valores.

In [2]:
arr = np.arange(0,10) #Creamos un vector de 10 entradas
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr ** 3 #Cada entrada se elava al cuadrada

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [4]:
arr + arr #Se aplica una suma por entradda del vector con sigo mismo

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr #Se multiplica cada entrada por su entrada correspondiente del otro vector

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr - arr #Se resta cada entrada con la correspondiente del mismo tamaño de vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

La siguiente celda generará un *Warning* sobre la división por cero, ¡pero no un arrojará *Error*! Simplemente llena la posición con *nan*.

In [7]:
arr / arr #Se divide cada entrada por la correspondiente al otro vector, en donde se divide con un cero abajo se
#guarda como nulo, por el calculo indeterminado

/var/folders/m5/cfc15px573ld6bgr5zly12_m0000gn/T/ipykernel_1210/1412164230.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr #Se divide cada entrada por la correspondiente al otro vector, en donde se divide con un cero abajo se


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
1 / arr #Se crea un nuevo vector con la misma dimension que la inicial, pero aca las entradas son dadas por la div 
#de 1 entre cada entrada

/var/folders/m5/cfc15px573ld6bgr5zly12_m0000gn/T/ipykernel_1210/1394770140.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr #Se crea un nuevo vector con la misma dimension que la inicial, pero aca las entradas son dadas por la div


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

#### Funciones Universales

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.sqrt(arr) #Se saca la raiz cuadada de cada entrada del vector

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.exp(arr) #Para cada entrada del vector se calcula la exponencial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [12]:
np.sin(arr) #Se calcula el seno de la entrada del vector

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.log(arr) #Se saca el log de cada entrada, para el cero el resultado es -inf por el comportamiento de la funcion

/var/folders/m5/cfc15px573ld6bgr5zly12_m0000gn/T/ipykernel_1210/2256441823.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #Se saca el log de cada entrada, para el cero el resultado es -inf por el comportamiento de la funcion


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#### Funciones Estadísticas

In [14]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr.mean() #Calculamos la media como con pandas

4.5

In [16]:
arr.max() #Maximo del vector

9

In [17]:
arr.min() #Minimo del vector

0

In [18]:
arr.var() #Varianza del vector

8.25

In [19]:
arr.std() #Desv estandar del vector

2.8722813232690143

### Vectorización

La vectorización es un método para lograr el paralelismo dentro de un solo núcleo de procesador.

Para expresarlo en términos sencillos, una sola instrucción se realiza sobre cada elemento individual de una matriz en un solo núcleo de CPU de manera paralela. La operación vectorizada puede reemplazar los bucles *for* tradicionales , ejecutarse más rápido, trabajar en diferentes tamaños de dimensión de matriz. Es una solución matricial que reemplaza explícitamente el bucle *for*.

In [20]:
import time
import numpy as np

In [21]:
size = 10000

In [22]:
np.random.seed(0)
vec_1 = np.random.random(size)
vec_2 = np.random.random(size)

In [23]:
vec_1

array([0.5488135 , 0.71518937, 0.60276338, ..., 0.75842952, 0.02378743,
       0.81357508])

In [24]:
# SIN Vectorización

tic = time.process_time()

python_product = np.zeros((size, size)) #Matriz cacaron de ceros

#Mediante un for se busca crear el producto punto de los dos vectores
for i in range(size):
    for j in range(size):
        python_product[i][j] = vec_1[i] * vec_2[j]

phyton_time = time.process_time() - tic
print('Tiempo de Python', phyton_time)

Tiempo de Python 67.84473899999999


In [25]:
# CON Vectorización

tic = time.process_time()
numpy_product = np.outer(vec_1, vec_2) #esta funcion realiza el producto punto en menor tiempo

numpy_time = time.process_time() - tic
print('Tiempo de Numpy', numpy_time)

Tiempo de Numpy 0.5920159999999868


In [29]:
numpy_product #Se crea una matriz de i renglones por j columnas, la cual en este caso es cuadrada

array([[0.41065957, 0.09889768, 0.21350116, ..., 0.24502095, 0.19764235,
        0.34349504],
       [0.5351533 , 0.12887906, 0.27822522, ..., 0.31930041, 0.25755872,
        0.44762747],
       [0.45102853, 0.10861959, 0.2344889 , ..., 0.26910718, 0.21707113,
        0.37726155],
       ...,
       [0.56750853, 0.13667105, 0.29504664, ..., 0.33860523, 0.27313066,
        0.47469091],
       [0.01779937, 0.00428656, 0.00925386, ..., 0.01062003, 0.00856649,
        0.01488823],
       [0.60877218, 0.14660843, 0.31649954, ..., 0.36322528, 0.29299004,
        0.50920578]])

In [26]:
np.sum(python_product != numpy_product) #Se comprueba que las matrices tengan el mismo tamaño

0

In [27]:
print('Mejora con Numpy', phyton_time / numpy_time)

Mejora con Numpy 114.59950237831664
